import { Task, TaskStats } from '@/types/task';

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Follow up with Acme Corp',
    description: 'Schedule demo call to showcase new features',
    priority: 'high',
    status: 'todo',
    dueDate: new Date(Date.now() + 86400000),
    assignee: 'Sarah Johnson',
    tags: ['sales', 'demo'],
    createdAt: new Date(Date.now() - 172800000),
  },
  {
    id: '2',
    title: 'Send proposal to Tech Solutions',
    description: 'Prepare and send detailed proposal with pricing',
    priority: 'urgent',
    status: 'in-progress',
    dueDate: new Date(Date.now()),
    assignee: 'Mike Chen',
    tags: ['proposal', 'sales'],
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: '3',
    title: 'Weekly team sync',
    description: 'Review progress and plan for next week',
    priority: 'medium',
    status: 'completed',
    dueDate: new Date(Date.now() - 86400000),
    assignee: 'Sarah Johnson',
    tags: ['meeting'],
    createdAt: new Date(Date.now() - 259200000),
    completedAt: new Date(Date.now() - 3600000),
  },
  {
    id: '4',
    title: 'Update CRM database',
    description: 'Import new leads from marketing campaign',
    priority: 'low',
    status: 'todo',
    dueDate: new Date(Date.now() + 172800000),
    assignee: 'Alex Rodriguez',
    tags: ['data', 'crm'],
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: '5',
    title: 'Call prospect - Global Industries',
    description: 'Initial discovery call to understand requirements',
    priority: 'high',
    status: 'in-progress',
    dueDate: new Date(Date.now() + 3600000),
    assignee: 'Mike Chen',
    tags: ['call', 'prospect'],
    createdAt: new Date(Date.now() - 43200000),
  },
  {
    id: '6',
    title: 'Prepare Q4 sales report',
    description: 'Compile sales data and create presentation',
    priority: 'medium',
    status: 'todo',
    dueDate: new Date(Date.now() + 259200000),
    assignee: 'Sarah Johnson',
    tags: ['report', 'analysis'],
    createdAt: new Date(Date.now() - 172800000),
  },
];

export const mockStats: TaskStats = {
  total: 6,
  completed: 1,
  inProgress: 2,
  overdue: 0,
  dueToday: 1,
};
