import { Task, TaskStats } from '@/types/task';
import { Lead } from '@/types/lead';
import { Contact } from '@/types/contact';
import { Deal } from '@/types/pipeline';
import { calculateInvoiceTotal } from '@/types/invoice';

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Follow up with Acme Corp',
    description: 'Schedule demo call to showcase new features',
    priority: 'high',
    status: 'todo',
    dueDate: new Date(Date.now() + 86400000),
    assignedTo: 'Sarah Johnson',
    tags: ['sales', 'demo'],
    createdAt: new Date(Date.now() - 172800000),
  },
  {
    id: '2',
    title: 'Send proposal to Tech Solutions',
    description: 'Prepare and send detailed proposal with pricing',
    priority: 'urgent',
    status: 'in-progress',
    dueDate: new Date(Date.now()),
    assignedTo: 'Mike Chen',
    tags: ['proposal', 'sales'],
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: '3',
    title: 'Weekly team sync',
    description: 'Review progress and plan for next week',
    priority: 'medium',
    status: 'completed',
    dueDate: new Date(Date.now() - 86400000),
    assignedTo: 'Sarah Johnson',
    tags: ['meeting'],
    createdAt: new Date(Date.now() - 259200000),
    completedAt: new Date(Date.now() - 3600000),
  },
  {
    id: '4',
    title: 'Update CRM database',
    description: 'Import new leads from marketing campaign',
    priority: 'low',
    status: 'todo',
    dueDate: new Date(Date.now() + 172800000),
    assignedTo: 'Alex Rodriguez',
    tags: ['data', 'crm'],
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: '5',
    title: 'Call prospect - Global Industries',
    description: 'Initial discovery call to understand requirements',
    priority: 'high',
    status: 'in-progress',
    dueDate: new Date(Date.now() + 3600000),
    assignedTo: 'Mike Chen',
    tags: ['call', 'prospect'],
    createdAt: new Date(Date.now() - 43200000),
  },
  {
    id: '6',
    title: 'Prepare Q4 sales report',
    description: 'Compile sales data and create presentation',
    priority: 'medium',
    status: 'todo',
    dueDate: new Date(Date.now() + 259200000),
    assignedTo: 'Sarah Johnson',
    tags: ['report', 'analysis'],
    createdAt: new Date(Date.now() - 172800000),
  },
];

export const mockStats: TaskStats = {
  total: 6,
  completed: 1,
  inProgress: 2,
  overdue: 0,
  dueToday: 1,
};

export const mockLeads: Lead[] = [
  {
    id: 'L001',
    name: 'Rajesh Kumar',
    company: 'Tech Innovations Pvt Ltd',
    email: 'rajesh.kumar@techinnovations.in',
    phone: '+91 98765 43210',
    whatsapp: '+91 98765 43210',
    source: 'web-form',
    status: 'new',
    priority: 'high',
    estimatedValue: 500000,
    assignedTo: 'Priya Sharma',
    notes: 'Interested in enterprise CRM solution for 50+ users',
    createdAt: new Date(Date.now() - 3600000),
    nextFollowUpAt: new Date(Date.now() + 86400000),
    tags: ['enterprise', 'hot-lead'],
    website: 'https://techinnovations.in',
    linkedIn: 'https://linkedin.com/in/rajeshkumar',
    twitter: 'https://twitter.com/rajeshkumar',
  },
  {
    id: 'L002',
    name: 'Amit Patel',
    company: 'Mumbai Traders',
    email: 'amit@mumbaitraders.com',
    phone: '+91 98234 56789',
    whatsapp: '+91 98234 56789',
    source: 'whatsapp',
    status: 'contacted',
    priority: 'medium',
    estimatedValue: 150000,
    assignedTo: 'Rahul Verma',
    notes: 'Looking for GST-compliant invoicing solution',
    createdAt: new Date(Date.now() - 172800000),
    lastContactedAt: new Date(Date.now() - 86400000),
    nextFollowUpAt: new Date(Date.now() + 172800000),
    tags: ['gst', 'invoicing'],
    website: 'https://mumbaitraders.com',
    linkedIn: 'https://linkedin.com/in/amitpatel',
  },
  {
    id: 'L003',
    name: 'Sunita Reddy',
    company: 'Hyderabad Exports',
    email: 'sunita@hyderabadexports.in',
    phone: '+91 99876 54321',
    whatsapp: '+91 99876 54321',
    source: 'call',
    status: 'qualified',
    priority: 'urgent',
    estimatedValue: 800000,
    assignedTo: 'Priya Sharma',
    notes: 'Ready to proceed. Needs multi-language support in Telugu and English',
    createdAt: new Date(Date.now() - 259200000),
    lastContactedAt: new Date(Date.now() - 43200000),
    nextFollowUpAt: new Date(Date.now() + 43200000),
    tags: ['qualified', 'multi-language', 'export'],
    website: 'https://hyderabadexports.in',
    linkedIn: 'https://linkedin.com/in/sunitareddy',
    facebook: 'https://facebook.com/hyderabadexports',
  },
  {
    id: 'L004',
    name: 'Vikram Singh',
    company: 'Delhi Retail Chain',
    email: 'vikram@delhiretail.co.in',
    phone: '+91 97123 45678',
    source: 'referral',
    status: 'proposal',
    priority: 'high',
    estimatedValue: 350000,
    assignedTo: 'Rahul Verma',
    notes: 'Referred by existing client. Interested in UPI payment integration',
    createdAt: new Date(Date.now() - 432000000),
    lastContactedAt: new Date(Date.now() - 172800000),
    nextFollowUpAt: new Date(Date.now() + 86400000),
    tags: ['referral', 'upi', 'retail'],
  },
  {
    id: 'L005',
    name: 'Meera Nair',
    company: 'Kerala Spices Co',
    email: 'meera@keralaspices.com',
    phone: '+91 98567 89012',
    source: 'social-media',
    status: 'new',
    priority: 'low',
    estimatedValue: 75000,
    assignedTo: 'Anjali Desai',
    notes: 'Small business owner looking for basic CRM features',
    createdAt: new Date(Date.now() - 86400000),
    nextFollowUpAt: new Date(Date.now() + 259200000),
    tags: ['small-business', 'basic'],
  },
  {
    id: 'L006',
    name: 'Arjun Mehta',
    company: 'Gujarat Textiles',
    email: 'arjun@gujarattextiles.in',
    phone: '+91 96789 01234',
    source: 'missed-call',
    status: 'contacted',
    priority: 'medium',
    estimatedValue: 250000,
    assignedTo: 'Priya Sharma',
    notes: 'Captured via missed call service. Interested in WhatsApp integration',
    createdAt: new Date(Date.now() - 345600000),
    lastContactedAt: new Date(Date.now() - 259200000),
    nextFollowUpAt: new Date(Date.now() + 86400000),
    tags: ['whatsapp', 'textile', 'missed-call'],
  },
  {
    id: 'L007',
    name: 'Kavita Deshmukh',
    company: 'Pune Manufacturing',
    email: 'kavita@punemanuf.co.in',
    phone: '+91 95432 10987',
    source: 'email',
    status: 'negotiation',
    priority: 'urgent',
    estimatedValue: 600000,
    assignedTo: 'Rahul Verma',
    notes: 'In final stages. Needs Tally integration and regional language support',
    createdAt: new Date(Date.now() - 518400000),
    lastContactedAt: new Date(Date.now() - 86400000),
    nextFollowUpAt: new Date(Date.now() + 43200000),
    tags: ['tally', 'manufacturing', 'closing-soon'],
  },
  {
    id: 'L008',
    name: 'Suresh Iyer',
    company: 'Chennai IT Services',
    email: 'suresh@chennaiit.com',
    phone: '+91 94321 09876',
    source: 'web-form',
    status: 'won',
    priority: 'high',
    estimatedValue: 450000,
    assignedTo: 'Anjali Desai',
    notes: 'Deal closed! Implementation to start next week',
    createdAt: new Date(Date.now() - 864000000),
    lastContactedAt: new Date(Date.now() - 172800000),
    tags: ['won', 'it-services', 'implementation'],
  },
];

export const mockContacts: Contact[] = [
  {
    id: 'C001',
    name: 'Rajesh Kumar',
    company: 'Tech Innovations Pvt Ltd',
    designation: 'CEO & Founder',
    email: 'rajesh@techinnovations.in',
    phone: '+91 98765 43210',
    whatsapp: '+91 98765 43210',
    type: 'customer',
    industry: 'technology',
    companySize: '50-200',
    gstNumber: '29ABCDE1234F1Z5',
    panNumber: 'ABCDE1234F',
    address: {
      street: '123, Electronic City',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560100',
      country: 'India',
    },
    website: 'https://techinnovations.in',
    linkedIn: 'https://linkedin.com/in/rajeshkumar',
    notes: 'Key decision maker. Prefers morning calls. Very interested in automation features.',
    createdAt: new Date(Date.now() - 7776000000),
    updatedAt: new Date(Date.now() - 86400000),
    tags: ['vip', 'enterprise', 'recurring'],
    assignedTo: 'Priya Sharma',
    lifetimeValue: 2500000,
  },
  {
    id: 'C002',
    name: 'Sunita Reddy',
    company: 'Hyderabad Exports',
    designation: 'Managing Director',
    email: 'sunita@hyderabadexports.in',
    phone: '+91 99876 54321',
    alternatePhone: '+91 40 2345 6789',
    whatsapp: '+91 99876 54321',
    type: 'customer',
    industry: 'export',
    companySize: '200-500',
    gstNumber: '36FGHIJ5678K1L2',
    panNumber: 'FGHIJ5678K',
    address: {
      street: '456, Hitech City',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500081',
      country: 'India',
    },
    website: 'https://hyderabadexports.in',
    notes: 'Needs multi-language support in Telugu. Interested in Tally integration.',
    createdAt: new Date(Date.now() - 5184000000),
    updatedAt: new Date(Date.now() - 172800000),
    tags: ['enterprise', 'export', 'multi-language'],
    assignedTo: 'Priya Sharma',
    lifetimeValue: 1800000,
  },
  {
    id: 'C003',
    name: 'Amit Patel',
    company: 'Mumbai Traders',
    designation: 'Partner',
    email: 'amit@mumbaitraders.com',
    phone: '+91 98234 56789',
    whatsapp: '+91 98234 56789',
    type: 'prospect',
    industry: 'retail',
    companySize: '10-50',
    gstNumber: '27KLMNO9012P1Q3',
    address: {
      street: '789, Andheri West',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400053',
      country: 'India',
    },
    notes: 'Looking for GST-compliant invoicing. Budget conscious.',
    createdAt: new Date(Date.now() - 2592000000),
    updatedAt: new Date(Date.now() - 259200000),
    tags: ['gst', 'invoicing', 'small-business'],
    assignedTo: 'Rahul Verma',
    lifetimeValue: 0,
  },
  {
    id: 'C004',
    name: 'Vikram Singh',
    company: 'Delhi Retail Chain',
    designation: 'Operations Head',
    email: 'vikram@delhiretail.co.in',
    phone: '+91 97123 45678',
    whatsapp: '+91 97123 45678',
    type: 'customer',
    industry: 'retail',
    companySize: '100-200',
    gstNumber: '07RSTUV3456W1X4',
    panNumber: 'RSTUV3456W',
    address: {
      street: '321, Connaught Place',
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110001',
      country: 'India',
    },
    website: 'https://delhiretail.co.in',
    notes: 'Referred by existing client. Needs UPI payment integration for retail outlets.',
    createdAt: new Date(Date.now() - 8640000000),
    updatedAt: new Date(Date.now() - 432000000),
    tags: ['referral', 'upi', 'retail', 'recurring'],
    assignedTo: 'Rahul Verma',
    lifetimeValue: 850000,
  },
  {
    id: 'C005',
    name: 'Kavita Deshmukh',
    company: 'Pune Manufacturing',
    designation: 'Finance Director',
    email: 'kavita@punemanuf.co.in',
    phone: '+91 95432 10987',
    alternatePhone: '+91 20 1234 5678',
    type: 'customer',
    industry: 'manufacturing',
    companySize: '500+',
    gstNumber: '27YZABC7890D1E5',
    panNumber: 'YZABC7890D',
    address: {
      street: '654, Pimpri-Chinchwad',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411018',
      country: 'India',
    },
    website: 'https://punemanuf.co.in',
    linkedIn: 'https://linkedin.com/in/kavitadeshmukh',
    notes: 'Large enterprise customer. Needs Tally integration and regional language support.',
    createdAt: new Date(Date.now() - 15552000000),
    updatedAt: new Date(Date.now() - 86400000),
    tags: ['enterprise', 'tally', 'manufacturing', 'vip'],
    assignedTo: 'Rahul Verma',
    lifetimeValue: 3200000,
  },
  {
    id: 'C006',
    name: 'Arjun Mehta',
    company: 'Gujarat Textiles',
    designation: 'Owner',
    email: 'arjun@gujarattextiles.in',
    phone: '+91 96789 01234',
    whatsapp: '+91 96789 01234',
    type: 'customer',
    industry: 'textile',
    companySize: '50-100',
    gstNumber: '24FGHJK1234L1M6',
    address: {
      street: '987, Textile Market',
      city: 'Ahmedabad',
      state: 'Gujarat',
      pincode: '380001',
      country: 'India',
    },
    notes: 'Captured via missed call service. Interested in WhatsApp integration for customer communication.',
    createdAt: new Date(Date.now() - 6048000000),
    updatedAt: new Date(Date.now() - 518400000),
    tags: ['whatsapp', 'textile', 'missed-call'],
    assignedTo: 'Priya Sharma',
    lifetimeValue: 550000,
  },
];

export const mockDeals: Deal[] = [
  {
    id: 'D001',
    title: 'Enterprise CRM Implementation',
    company: 'Tech Innovations Pvt Ltd',
    contactName: 'Rajesh Kumar',
    stage: 'negotiation',
    value: 500000,
    probability: 80,
    expectedCloseDate: new Date(Date.now() + 604800000), // 1 week
    createdAt: new Date(Date.now() - 2592000000), // 30 days ago
    updatedAt: new Date(Date.now() - 86400000),
    assignedTo: 'Priya Sharma',
    notes: '50+ user enterprise solution. Technical evaluation completed. Waiting on final approval from board.',
    tags: ['enterprise', 'hot-deal', 'technical-approved'],
    nextAction: 'Follow up with CFO for contract signing',
    source: 'website',
  },
  {
    id: 'D002',
    title: 'GST Invoicing Solution',
    company: 'Mumbai Traders',
    contactName: 'Amit Patel',
    stage: 'proposal',
    value: 150000,
    probability: 60,
    expectedCloseDate: new Date(Date.now() + 1209600000), // 2 weeks
    createdAt: new Date(Date.now() - 1728000000), // 20 days ago
    updatedAt: new Date(Date.now() - 259200000),
    assignedTo: 'Rahul Verma',
    notes: 'Small business looking for GST-compliant invoicing. Budget conscious but good fit.',
    tags: ['gst', 'invoicing', 'small-business'],
    nextAction: 'Send revised proposal with discount',
    source: 'whatsapp',
  },
  {
    id: 'D003',
    title: 'Multi-language CRM for Exports',
    company: 'Hyderabad Exports',
    contactName: 'Sunita Reddy',
    stage: 'negotiation',
    value: 800000,
    probability: 85,
    expectedCloseDate: new Date(Date.now() + 345600000), // 4 days
    createdAt: new Date(Date.now() - 3456000000), // 40 days ago
    updatedAt: new Date(Date.now() - 43200000),
    assignedTo: 'Priya Sharma',
    notes: 'Large export company. Needs Telugu and English support. Ready to sign.',
    tags: ['enterprise', 'multi-language', 'export', 'closing-soon'],
    nextAction: 'Schedule contract signing meeting',
    source: 'referral',
  },
  {
    id: 'D004',
    title: 'UPI Payment Integration',
    company: 'Delhi Retail Chain',
    contactName: 'Vikram Singh',
    stage: 'qualified',
    value: 350000,
    probability: 70,
    expectedCloseDate: new Date(Date.now() + 1814400000), // 3 weeks
    createdAt: new Date(Date.now() - 1296000000), // 15 days ago
    updatedAt: new Date(Date.now() - 172800000),
    assignedTo: 'Rahul Verma',
    notes: 'Referred by existing client. Interested in UPI/Razorpay integration for retail outlets.',
    tags: ['referral', 'upi', 'retail', 'payment-gateway'],
    nextAction: 'Demo UPI payment features',
    source: 'referral',
  },
  {
    id: 'D005',
    title: 'Basic CRM for Small Business',
    company: 'Kerala Spices Co',
    contactName: 'Meera Nair',
    stage: 'lead',
    value: 75000,
    probability: 40,
    expectedCloseDate: new Date(Date.now() + 2592000000), // 30 days
    createdAt: new Date(Date.now() - 604800000), // 7 days ago
    updatedAt: new Date(Date.now() - 259200000),
    assignedTo: 'Anjali Desai',
    notes: 'Small business owner. Budget limited but interested in basic features.',
    tags: ['small-business', 'basic', 'budget-conscious'],
    nextAction: 'Schedule discovery call',
    source: 'social-media',
  },
  {
    id: 'D006',
    title: 'WhatsApp Business Integration',
    company: 'Gujarat Textiles',
    contactName: 'Arjun Mehta',
    stage: 'proposal',
    value: 250000,
    probability: 65,
    expectedCloseDate: new Date(Date.now() + 1209600000), // 2 weeks
    createdAt: new Date(Date.now() - 2160000000), // 25 days ago
    updatedAt: new Date(Date.now() - 432000000),
    assignedTo: 'Priya Sharma',
    notes: 'Captured via missed call service. Wants WhatsApp integration for customer communication.',
    tags: ['whatsapp', 'textile', 'missed-call', 'integration'],
    nextAction: 'Present WhatsApp integration demo',
    source: 'missed-call',
  },
  {
    id: 'D007',
    title: 'Tally Integration & Regional Languages',
    company: 'Pune Manufacturing',
    contactName: 'Kavita Deshmukh',
    stage: 'proposal',
    value: 600000,
    probability: 75,
    expectedCloseDate: new Date(Date.now() + 864000000), // 10 days
    createdAt: new Date(Date.now() - 4320000000), // 50 days ago
    updatedAt: new Date(Date.now() - 86400000),
    assignedTo: 'Rahul Verma',
    notes: 'Large manufacturing unit. Needs Tally integration and Marathi language support.',
    tags: ['tally', 'manufacturing', 'enterprise', 'multi-language'],
    nextAction: 'Demo Tally sync and language features',
    source: 'outbound',
  },
  {
    id: 'D008',
    title: 'IT Services CRM',
    company: 'Chennai IT Services',
    contactName: 'Suresh Iyer',
    stage: 'closed-won',
    value: 450000,
    probability: 100,
    expectedCloseDate: new Date(Date.now() - 604800000), // Closed 1 week ago
    createdAt: new Date(Date.now() - 5184000000), // 60 days ago
    updatedAt: new Date(Date.now() - 604800000),
    assignedTo: 'Anjali Desai',
    notes: 'Deal closed! Implementation starting next week. Great reference customer.',
    tags: ['won', 'it-services', 'implementation', 'reference'],
    nextAction: 'Start implementation kickoff',
    source: 'website',
  },
  {
    id: 'D009',
    title: 'Real Estate CRM',
    company: 'Bangalore Properties',
    contactName: 'Deepak Nair',
    stage: 'closed-lost',
    value: 300000,
    probability: 0,
    expectedCloseDate: new Date(Date.now() - 1209600000), // Lost 2 weeks ago
    createdAt: new Date(Date.now() - 6048000000), // 70 days ago
    updatedAt: new Date(Date.now() - 1209600000),
    assignedTo: 'Rahul Verma',
    notes: 'Lost to competitor. Price was main concern. Keep for future opportunities.',
    tags: ['lost', 'real-estate', 'price-sensitive'],
    nextAction: 'Add to nurture campaign',
    source: 'website',
  },
  {
    id: 'D010',
    title: 'Pharmaceutical CRM with Compliance',
    company: 'MediCare Pharma',
    contactName: 'Dr. Anita Kulkarni',
    stage: 'qualified',
    value: 550000,
    probability: 65,
    expectedCloseDate: new Date(Date.now() + 2592000000), // 30 days
    createdAt: new Date(Date.now() - 1728000000), // 20 days ago
    updatedAt: new Date(Date.now() - 259200000),
    assignedTo: 'Priya Sharma',
    notes: 'Pharmaceutical company needs CRM with regulatory compliance features.',
    tags: ['healthcare', 'pharma', 'compliance', 'enterprise'],
    nextAction: 'Prepare compliance feature documentation',
    source: 'inbound',
  },
];

export const mockInvoices = (() => {
  const companyDetails = {
    companyName: "Bharat CRM Solutions Pvt Ltd",
    companyGSTIN: "29XYZAB5678C1D2",
    companyAddress: "456, MG Road, Bangalore",
    companyState: "Karnataka",
    companyPincode: "560001",
  };

  // Invoice 1: Intra-state (Karnataka to Karnataka) - CGST + SGST
  const inv1Items = [
    {
      id: "li-1",
      description: "CRM License - Professional Plan (Annual)",
      hsnSac: "998314",
      quantity: 10,
      unit: "users",
      rate: 1499,
      discount: 10,
      amount: 0,
      taxRate: 18 as const,
    },
    {
      id: "li-2",
      description: "WhatsApp Business API Setup",
      hsnSac: "998313",
      quantity: 1,
      unit: "service",
      rate: 25000,
      discount: 0,
      amount: 0,
      taxRate: 18 as const,
    },
  ];
  const inv1Calc = calculateInvoiceTotal(inv1Items, "Karnataka", "Karnataka");

  // Invoice 2: Inter-state (Karnataka to Telangana) - IGST
  const inv2Items = [
    {
      id: "li-3",
      description: "CRM Implementation Services",
      hsnSac: "998313",
      quantity: 1,
      unit: "service",
      rate: 75000,
      discount: 0,
      amount: 0,
      taxRate: 18 as const,
    },
    {
      id: "li-4",
      description: "Training and Support (3 months)",
      hsnSac: "999293",
      quantity: 3,
      unit: "months",
      rate: 5000,
      discount: 5,
      amount: 0,
      taxRate: 18 as const,
    },
  ];
  const inv2Calc = calculateInvoiceTotal(inv2Items, "Karnataka", "Telangana");

  // Invoice 3: Inter-state (Karnataka to Delhi) - IGST
  const inv3Items = [
    {
      id: "li-5",
      description: "CRM License - Enterprise Plan (Annual)",
      hsnSac: "998314",
      quantity: 50,
      unit: "users",
      rate: 2999,
      discount: 15,
      amount: 0,
      taxRate: 18 as const,
    },
  ];
  const inv3Calc = calculateInvoiceTotal(inv3Items, "Karnataka", "Delhi");

  // Invoice 4: Intra-state (Karnataka to Karnataka) - CGST + SGST
  const inv4Items = [
    {
      id: "li-6",
      description: "Custom Integration Development",
      hsnSac: "998313",
      quantity: 40,
      unit: "hours",
      rate: 2500,
      discount: 0,
      amount: 0,
      taxRate: 18 as const,
    },
  ];
  const inv4Calc = calculateInvoiceTotal(inv4Items, "Karnataka", "Karnataka");

  return [
    {
      id: "inv-001",
      invoiceNumber: "INV-2025-001",
      ...companyDetails,
      customerId: "C001",
      customerName: "Tech Innovations Pvt Ltd",
      customerEmail: "finance@techinnovations.in",
      customerAddress: "123, Electronic City, Bangalore",
      customerState: "Karnataka",
      customerPincode: "560100",
      customerGSTIN: "29ABCDE1234F1Z5",
      issueDate: "2025-01-15",
      dueDate: "2025-02-14",
      status: "sent" as const,
      lineItems: inv1Items,
      ...inv1Calc,
      notes: "Thank you for your business! Payment due within 30 days.",
      termsAndConditions: "Late payment charges applicable after due date.",
    },
    {
      id: "inv-002",
      invoiceNumber: "INV-2025-002",
      ...companyDetails,
      customerId: "C002",
      customerName: "Hyderabad Exports",
      customerEmail: "accounts@hyderabadexports.in",
      customerAddress: "456, Hitech City, Hyderabad",
      customerState: "Telangana",
      customerPincode: "500081",
      customerGSTIN: "36FGHIJ5678K1L2",
      issueDate: "2025-01-18",
      dueDate: "2025-02-17",
      status: "paid" as const,
      paymentMethod: "upi" as const,
      paymentDate: "2025-01-20",
      lineItems: inv2Items,
      ...inv2Calc,
      notes: "Paid via UPI - Thank you!",
      termsAndConditions: "Payment received. Invoice closed.",
    },
    {
      id: "inv-003",
      invoiceNumber: "INV-2025-003",
      ...companyDetails,
      customerId: "C004",
      customerName: "Delhi Retail Chain",
      customerEmail: "billing@delhiretail.co.in",
      customerAddress: "321, Connaught Place, New Delhi",
      customerState: "Delhi",
      customerPincode: "110001",
      customerGSTIN: "07RSTUV3456W1X4",
      issueDate: "2024-12-20",
      dueDate: "2025-01-19",
      status: "overdue" as const,
      lineItems: inv3Items,
      ...inv3Calc,
      notes: "Payment overdue - please remit immediately",
      termsAndConditions: "Late payment interest @ 2% per month applicable.",
    },
    {
      id: "inv-004",
      invoiceNumber: "INV-2025-004",
      ...companyDetails,
      customerId: "C001",
      customerName: "Tech Innovations Pvt Ltd",
      customerEmail: "finance@techinnovations.in",
      customerAddress: "123, Electronic City, Bangalore",
      customerState: "Karnataka",
      customerPincode: "560100",
      customerGSTIN: "29ABCDE1234F1Z5",
      issueDate: "2025-01-22",
      dueDate: "2025-02-21",
      status: "draft" as const,
      lineItems: inv4Items,
      ...inv4Calc,
      notes: "Draft - pending approval",
      termsAndConditions: "Payment due within 30 days of invoice date.",
    },
  ];
})();

export const mockInvoiceStats = {
  totalInvoices: mockInvoices.length,
  paidAmount: mockInvoices.filter(inv => inv.status === 'paid').reduce((sum, inv) => sum + inv.total, 0),
  pendingAmount: mockInvoices.filter(inv => inv.status === 'sent').reduce((sum, inv) => sum + inv.total, 0),
  overdueAmount: mockInvoices.filter(inv => inv.status === 'overdue').reduce((sum, inv) => sum + inv.total, 0),
};
